version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: wico_server_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_DB_PASSWORD}
      MYSQL_DATABASE: ${DEV_DB_DATABASE}
      MYSQL_USER: ${DEV_DB_USERNAME}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - '${DEV_DB_PORT}:3306'

  # networks:
  #   default:
  #     name:
